### ISSUE TITLE
Database ER Diagram

### ISSUE THREAD

**Issue by jespernpedersen** [jespernpedersen/dissertation-project#11]

**Comment by DiogoGeada** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/jxyxjgchlflw) to **5**, the maximum vote was **5** story points.

**Comment by DiogoGeada** [comment]
![Diagrama em branco](https://user-images.githubusercontent.com/18559792/144626233-50e2b363-4447-4a42-ae54-a55cfd516a5a.jpeg)

**Comment by DiogoGeada** [comment]
![Diagrama em branco - Página 2](https://user-images.githubusercontent.com/18559792/144626248-1c65bee3-ab85-4975-8b60-31b27ebc3da4.png)
