### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by jespernpedersen** [jespernpedersen/dissertation-project#2]

**Comment by DiogoGeada** [comment]
![image](https://user-images.githubusercontent.com/18559792/141293835-6b1a1caa-0f54-49b7-8dba-04cdbb9db027.png)

**Comment by akram0171** [comment]
<img width="307" alt="userstory" src="https://user-images.githubusercontent.com/71497578/141293990-507c4c44-99dc-4958-bebd-e77aeaaad641.PNG">
