### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by jespernpedersen** [jespernpedersen/dissertation-project#3]
Write an interview script to gather data on personas

Waiting for #13 to be completed

**Comment by jespernpedersen** [comment]
![image](https://user-images.githubusercontent.com/25395486/141094518-f3b75344-d24a-43f4-9249-ea3f5a112e3c.png)

**Comment by jespernpedersen** [comment]
https://personagenerator.com/ac5b37d2-4209-11ec-982a-ebc0a7f7c4cc/ac5b37d3-4209-11ec-982a-c7290a39963f

**Comment by akram0171** [comment]
[Ali Kassem's persona _ PersonaGenerator.pdf](https://github.com/jespernpedersen/dissertation-project/files/7511871/Ali.Kassem.s.persona._.PersonaGenerator.pdf)

**Comment by akram0171** [comment]
![0001](https://user-images.githubusercontent.com/71497578/141096134-44d7adaa-cd9e-490f-964f-dde8776b8adf.jpg)
