### ISSUE TITLE
App Design

### ISSUE THREAD

**Issue by DiogoGeada** [jespernpedersen/dissertation-project#58]
Design front page, search results page and try other navigation options for restaurants detail page

**Comment by akram0171** [comment]
![Dissertation-06](https://user-images.githubusercontent.com/71497578/144819219-cbcfe2d0-5106-4d27-911c-0068d6c6abc8.png)

**Comment by akram0171** [comment]
![Dissertation-05](https://user-images.githubusercontent.com/71497578/145229883-668d62df-688c-4cc0-853b-3abae27bb24d.png)

**Comment by akram0171** [comment]
![DissertationUpdatedDesign-01](https://user-images.githubusercontent.com/71497578/146543104-bb7415c4-10ce-4852-882c-7ae6cb63ed66.jpg)

**Comment by akram0171** [comment]
![DissertationUpdatedDesignjpg-01](https://user-images.githubusercontent.com/71497578/146543609-ffe46615-9356-4434-bec3-cd5125610a26.jpg)
![DissertationUpdatedDesignjpg-02](https://user-images.githubusercontent.com/71497578/146543611-ee8e6534-cebe-4e4b-9d9a-9c938a3b5215.jpg)
![DissertationUpdatedDesignjpg-03](https://user-images.githubusercontent.com/71497578/146543617-d32651eb-0f87-4bee-8d17-36f24d0b0484.jpg)
![DissertationUpdatedDesignjpg-04](https://user-images.githubusercontent.com/71497578/146543620-ef59db35-65de-42f2-a020-c22f4480078d.jpg)
![DissertationUpdatedDesignjpg-05](https://user-images.githubusercontent.com/71497578/146543623-8767c9de-98d9-4f10-8041-ea86511d35bf.jpg)
